Analyse the results of the batch search done in the cluster.

In [1]:
!pwd

/Users/rosamartinezcorral/Dropbox (HMS)/papers/github_repos/allostery-paper


In [3]:
import sys,os
sys.path.append('../../../work2/shared/utilsGRF')
sys.path.append("./bin")
import BoundaryFinder as BF
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.optimize import minimize
import matplotlib.gridspec as gridspec

In [4]:
import utils_matchHill_repo as utils_matchHill

In [5]:
def plot_pars(pars,n_sites=0,GRFfunc=None,psfunc=None):
    #xvals=np.logspace(-3,0.5,5000)
    npoints=1000
    x05=1
    xvals_h=np.linspace(0.005,5,1000)
    xvals_h=np.logspace(np.log10(0.01),1,npoints)
    hill_line=[BF.position_steepness_hill(n) for n in np.arange(2,n_sites+2,0.1)]
    hill_x=[x[0] for x in hill_line]
    hill_y=[x[1] for x in hill_line]
    fig,axes=plt.subplots(1,2,figsize=(10,4))
    ax=axes[0]
    ax.plot(hill_x,hill_y,color="magenta",linestyle="--")
    for n in range(2,n_sites+2):
        ph,sh=BF.position_steepness_hill(n)
        ax.scatter(ph,sh,color="magenta",marker="x")
        ax.text(ph,sh,"n=%d"%n)
    ps,stp,x05=psfunc(pars)
    print(ps,stp)
    ax.scatter(ps,stp,color="b")
    ax.set_xlabel("position")
    ax.set_ylabel("steepness")
   
    ax=axes[1]
    xvals=xvals_h
    #xvals=np.logspace(np.log10(x05)-2,np.log10(x05)+2,npoints)
    print("function evaluated between %2.2f and %2.2f"%(min(xvals),max(xvals)))
    values=[GRFfunc(pars,x*x05) for x in xvals]
    values=np.array(values)
    
    #print("xhalf",x05)
    #values_norm=[GRFfunc(pars,x*x05) for x in xvals] #compute normalised GRF
    #ax.plot(xvals,values_norm,color="blue",label="coarse grained formula\n normalised by x05",linestyle="-",linewidth=3)
    ax.plot(xvals,values,color="blue",label="coarse grained formula",linestyle="-",linewidth=3)

    ax.plot(xvals_h,utils_matchHill.hill(n_sites,xvals_h),color="magenta",label="Hill",linestyle="-",marker="o",ms=2)
    ax.set_xlabel("x")
    ax.set_ylabel("fractional saturation")
    ax.set_xlim(0.005,5)
    ax.legend()
    plt.tight_layout()
    plt.show()

In [6]:

import CG_c4_N6_samesitesFalse


In [6]:
folder="./2021_03_O2_revision_allostery/final"

In [7]:
betas=[0.25,0.5,0.75]

n_sites_list=[4,5,6]
results=dict()
for sites in n_sites_list:
    results[sites]=[]
        

  

In [26]:

allfiles=[x for x in os.listdir(folder) if "final" in x]
plimc=6
plim=4
c=4

for ns,n_sites in enumerate(n_sites_list):

    basename="final_nt%d_plim%d_plimc%d_c%d"%(n_sites,plim,plimc,c) #,beta)
    files=[x for x in allfiles if basename in x]#+[x for x in allfiles_cont if basename in x]
    print("-------")
    errors=[]
    files_read=[]
    for file in sorted(files):
        #print(file)

        f=open(os.path.join(folder,file),"r")
        lines=f.readlines()
        f.close()

        if len(lines)>2: #for a few, they were time killed
            #print(lines)
            error=float(lines[-2].split(":")[1].strip())
            l_p=lines[-1].split(":")[1].strip().split(",")
            parset=np.array(list(map(float,l_p)))
            results[key][n_sites][plimc][plim].append([parset,error,file])
            errors.append(error)
            files_read.append(file)
    print(n_sites,key,plimc,"min error", min(errors))
    print("#",n_sites,plimc,plim, "there are", len(errors))
    
        
            
                

-------
4 c4 6 min error 3.2752038252243603
# 4 6 4 there are 869
beta=0.25
seeds=
0 290
[  0  18  36  54  72  90 108 126 144 162]
[  0  18  36  54  72  90 108 126 144 162]
all equal? False
[5166 5184 5202]
seeds missing []
seeds added [5220]
beta=0.5
seeds=
1 290
[  1  19  37  55  73  91 109 127 145 163]
[  1  19  37  55  73  91 109 127 145 163]
all equal? True
[5167 5185 5203]
seeds missing []
seeds added []
beta=0.75
seeds=
2 289
[  2  20  38  56  74  92 110 128 146 164]
[  2  20  38  56  74  92 110 128 146 164]
all equal? False
[5168 5186 5204]
seeds missing [5204]
seeds added [272]
-------


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:48: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


4 c4 6 min error 3.2651563292463837
# 4 6 6 there are 870
beta=0.25
seeds=
3 290
[  3  21  39  57  75  93 111 129 147 165]
[  3  21  39  57  75  93 111 129 147 165]
all equal? True
[5169 5187 5205]
seeds missing []
seeds added []
beta=0.5
seeds=
4 290
[  4  22  40  58  76  94 112 130 148 166]
[  4  22  40  58  76  94 112 130 148 166]
all equal? True
[5170 5188 5206]
seeds missing []
seeds added []
beta=0.75
seeds=
5 290
[  5  23  41  59  77  95 113 131 149 167]
[  5  23  41  59  77  95 113 131 149 167]
all equal? True
[5171 5189 5207]
seeds missing []
seeds added []
-------
5 c4 6 min error 1.9804022935798837
# 5 6 4 there are 865
beta=0.25
seeds=
6 288
[  6  24  42  60  78  96 114 132 150 168]
[  6  24  42  60  78  96 114 132 150 168]
all equal? False
[5154 5172 5190]
seeds missing [5190]
seeds added [2364]
beta=0.5
seeds=
7 289
[  7  25  43  61  79  97 115 133 151 169]
[  7  25  43  61  79  97 115 133 151 169]
all equal? True
[5155 5173 5191]
seeds missing []
seeds added []
beta=0.75

In [9]:
from effective_pars import get_parameter_values as gpvc4


f="./bin/CG_c4_N6_samesitesFalse.cpp"
fname="void GRF_CG_c4_N6_samesitesFalse_x"
fh=open(f,"r")
get=False
lines=[]
for l in fh.readlines():
    if fname in l:
        #print(l)
        get=True
    if get:
        if l=="}\n":
            get=False
    if get:
        lines.append(l)
fh.close()

#the names of the effective parameters for 6 sites are the same irrespective of 2 or 4 conformations
parameters_names=[]
for l in lines:
    if "T" in l and "pars" in l:
        l_=l.strip().replace("T ","")
for l in lines:
    if "T K" in l and not "pars" in l:
        l_=l.strip().replace("T ","")
        #K_defs.append(l_)
        parameters_names.append(l_.split("=")[0])
for l in lines:
    if "T w" in l:
        #print(l.strip().replace("T ",""))
        l_=l.strip().replace("T ", "")
        parameters_names.append(l_.split("=")[0])
        #w_defs.append(l_)
        #

size_w=[]
for x in parameters_names[6:]:
    n_l=list(x[1:])
    dif=6-len(n_l)
    zeros=['0']*dif
    tuple_=tuple(map(int,zeros+n_l))
    size_w.append(tuple_)
    
size_w=np.array(size_w,dtype=[("fst","i4"),("se","i4"),("th","i4"),("fo","i4"),("fi","i4"),("si","i4")])

argsort_=np.argsort(size_w,order=["fst","se","th","fo","fi","si"])
argsort=[0,1,2,3,4,5]+list(argsort_+6)

parameters_names_tex=[]
for par in parameters_names:
    p_l=list(par)
    letter=p_l[0]
    numbers=p_l[1:]
    if letter=="K":
        newlab="$K^\emptyset"
    else:
        newlab="$\omega^\emptyset"
    site=numbers[0]
    newlab+=site
    
    if letter!="K" and len(numbers)>1:
        if len(numbers)>2:
            newlab+=",\{%s\}$"%",".join(numbers[1:])
        else:
            newlab+=",\{%s\}$"%(numbers[1])
    else:
        newlab+=",\emptyset$"
    parameters_names_tex.append(newlab)
        

In [ ]:
yticklabels=["$K_{c_k,%d,S}$"%(i+1) for i in range(6)]
xticklabels_4=["$c_%d$"%(i+1) for i in range(4)]
xticklabels_2=["$c_%d$"%(i+1) for i in range(2)]
c_conf=4
plimc=6
for c_conf in [4]:
    for n_target in n_sites_list:
        print("matching Hill %d"%n_target)
        #for beta in betas:
        #print("beta",beta)
        for plim in plims:
            print("parameter limit is",plim)

            print("#new combi------")
        
            key="c%d"%c_conf
            if c_conf==2:
                psfunc=CG_c2_N6_samesitesFalse.interfaceps_a_GRF_CG_c2_N6_samesitesFalse_x
                GRFfunc=CG_c2_N6_samesitesFalse.interface_GRF_CG_c2_N6_samesitesFalse_x
                gpv=gpvc2
            elif c_conf==4:
                psfunc=CG_c4_N6_samesitesFalse.interfaceps_a_GRF_CG_c4_N6_samesitesFalse_x
                GRFfunc=CG_c4_N6_samesitesFalse.interface_GRF_CG_c4_N6_samesitesFalse_x
                gpv=gpvc4
            results_errors=results[key][n_target][plimc][plim]
            results_n=[x[0] for x in results_errors]
            errors_n=[x[1] for x in results_errors]
            files_n=[x[2] for x in results_errors]
            print("n=%d"%n_target, "c=%d"%c_conf, "plim=%d"%plim)
            print(len(errors_n))
            if len(errors_n)==0:
                continue
            argsort_e=np.argsort(errors_n)
            j=0
            if min(errors_n)<2:
                max_plot=6
                max_error=3
            else:
                max_plot=3
                max_error=5
            for idx in argsort_e:
                #if j<max_plot: #plot only 3 best to start with
                error=errors_n[idx]
                if error<max_error and j<50:
                    print(idx, "j=%d"%j)
                    print(files_n[idx])
                    j+=1
                    parset=results_n[idx]
                    error=errors_n[idx]
                    print("error",errors_n[idx])
                    if error>10:
                        print("error>10. skipping")
                    else:
                    
                        #parset=l_[1] #.split(":")[1].strip()
                        print(",".join(map(str,parset)))
                        #parset=np.array(list(map(float,parset.split(","))))
                        plot_pars(parset,n_sites=n_target,psfunc=psfunc,GRFfunc=GRFfunc)
                        parvalues=gpv(parset)

                        fig=plt.figure(figsize=(18,2.3))
                        gs=gridspec.GridSpec(ncols=100,nrows=16,figure=fig)
                        g1=[0,11]
                        g2=[18,85]
                        g3=[90,100]
                        dx1=1

                        ax=fig.add_subplot(gs[0:11,g1[0]:g1[1]])
                        if c_conf==4:
                            mat=np.zeros((6,4))
                            c=0
                            for i in range(0,24,6):
                                pars_conf=parset[i:i+6]
                                print(pars_conf)
                                for s,site in enumerate(pars_conf):
                                    log10s=np.log10(site)
                                    mat[s,c]=log10s
                                c+=1
                        else:
                            mat=np.zeros((6,2))
                            c=0
                            for i in range(0,12,6):
                                pars_conf=parset[i:i+6]
                                print(pars_conf)
                                for s,site in enumerate(pars_conf):
                                    log10s=np.log10(site)
                                    mat[s,c]=log10s
                                c+=1
                            
                        im=ax.imshow(mat,cmap=plt.cm.Blues,aspect="auto")#vmin=-6,vmax=3

                        ax.set_yticks(np.arange(0,6))
                        
                        ax.set_yticklabels(yticklabels,useTex=True)
                        ax.set_xticks([])
                        #ax.set_xlabel("site")

                        #ax.set_xticks(np.arange(4))
                        #ax.set_xticklabels([1,2,3,4])
                        #ax.set_ylabel("conformation")

                        cax=fig.add_subplot(gs[0:11,g1[1]:g1[1]+dx1])
                        cb=plt.colorbar(im,ax=ax,cax=cax,shrink=0.9) #ticks=[-3,0,3] 
                        #cb.ax.set_yticklabels(["$10^{-3}$","$1$","$10^{3}$"],usetex=True)
                        #cb.ax.set_ylabel("$K_{ck,i,S})$")
                        ax=fig.add_subplot(gs[11:13,g1[0]:g1[1]])
                        if c_conf==4:
                            pars_conf=np.concatenate((np.array([1]),parset[-3:]))
                        else:
                            pars_conf=np.array([1,parset[-1]])
                        print(pars_conf)
                        mat_conf=pars_conf/np.sum(pars_conf) #probability empty conf
                        #print("min-max",mat_conf.min(),mat_conf.max())
                        cax=fig.add_subplot(gs[15,g1[0]:g1[1]])

                        if c_conf==4:
                            imc=ax.imshow(np.log10(mat_conf.reshape(1,4)),aspect="auto",cmap=plt.cm.summer)
                            ax.set_xticks(range(4))
                            ax.set_xticklabels(xticklabels_4,usetex=True)
                        else:
                            imc=ax.imshow(np.log10(mat_conf.reshape(1,2)),aspect="auto",cmap=plt.cm.summer)
                            ax.set_xticks(range(2))
                            ax.set_xticklabels(xticklabels_2,usetex=True)
                        
                        ticks=np.linspace(np.log10(np.min(mat_conf)),np.log10(np.max(mat_conf)),3)
                        cb=plt.colorbar(imc,orientation="horizontal",label="$Pr_(c_k)$",cax=cax,ticks=ticks)
                        cb.ax.set_xticks(ticks)
                        cb.ax.set_xticklabels(["%2.1e"%x for x in np.linspace(np.min(mat_conf),np.max(mat_conf),3)],rotation=90)
                        
                        ax.set_yticks([])
                        #ax.set_zlabel(,fontsize=16)
                        #ax.set_zticks(range(7))
                        #ax.set_zticklabels([-3,-2,-1,0,1,2,3])
                        #ax.view_init(30,-30)

                        ax = fig.add_subplot(gs[:, g2[0]:g2[1]])

                        parvalues_sorted=np.array(parvalues)[argsort]
                        values=[]
                        print("effective parameters")
                        for p,par in enumerate(parvalues_sorted):
                            log10p=np.log10(par)
                            values.append(log10p)
                            print(par,end=",")
                        print("")

                        ax.plot(range(len(values)),values,color="k",marker="o")
                        ax.set_xticks(np.arange(len(parvalues)))
                        #lab=ax.set_xticklabels(np.array(parameters_names_tex)[argsort],rotation=90,fontsize=9)
                        ax.set_ylabel("log$_{10}$(effective parameter)")
                        ax.set_xlim(-1,len(parvalues))
                        xvals=np.logspace(-3,0.5,5000)
                        #ax.set_ylim([-2.5,6])

                        ax=fig.add_subplot(gs[:,g3[0]:])

                        ps,stp,x05=psfunc(parset)
                        print(ps,stp)

                        values=[GRFfunc(parset,x) for x in xvals]
                        values=np.array(values)

                        print("xhalf",x05)
                        values_norm=[GRFfunc(parset,x*x05) for x in xvals] #compute normalised GRF
                        ax.plot(xvals,values_norm,color="k",label="allosteric model",linestyle="-",linewidth=2)

                        ax.plot(xvals,utils_matchHill.hill(n_target,xvals),color="gray",label="Hill n=%d"%n_target,linestyle=":",linewidth=2)
                        ax.set_xlabel("concentration (a.u.)")
                        ax.set_ylabel("average binding")
                        #ax.legend(bbox_to_anchor=(1,1))

                        ax.set_xticks([0,1,2,3])
                        ax.text(0,1,"H %d matched"%n_target,color="k") #colors[c_])
                        ax.spines['right'].set_visible(False)
                        ax.spines['top'].set_visible(False)
                        #plt.tight_layout()
                        #plt.savefig("n%d.pdf"%n_sites,bbox_inches="tight")
                        plt.show()